#!/bin/sh

# This script handles selecting the IV generation algorithm for crypt_types
# that use variable IV algorithms (ie. not loop-AES)

. /lib/partman/crypto_tools.sh

dev=$2
id=$3
part=$dev/$id

[ -f $part/method ] || exit 0
[ -f $part/cipher ] || exit 0
method=$(cat $part/method)
cipher=$(cat $part/cipher)

if [ "${method%/*}" = crypto ]; then
    type=${method#*/}
    crypto_dooption $part $type $cipher "ivalgorithm"
fi
