#!/bin/sh

. /lib/partman/definitions.sh
. /lib/partman/crypto_tools.sh

dev=$1
id=$2

cd $dev

# don't show crypto for already encrypted partitions
if [ -f crypt_realdev ]; then
    exit 0
fi

for type in $CRYPT_TYPES; do
    db_metaget partman/method_long/crypto/$type description
    printf "%s\t%s\n" $type "$RET"
done

