#!/bin/sh

type=$1
dev=$2
id=$3
part=$dev/$id

[ -d $dev/$id ] || mkdir $dev/$id

echo crypto/$type >$dev/$id/method
rm -f $dev/$id/use_filesystem
rm -f $dev/$id/format

# Choose sensible defaults for crypt_type
case $type in
    loop-AES)
        # cipher AES128 / keyfile
        [ -f $part/cipher ] || echo AES128 > $part/cipher
        [ -f $part/keytype ] || echo keyfile > $part/keytype
        ;;
    dm-crypt)
	[ -f $part/cipher ] || echo aes > $part/cipher
	[ -f $part/keysize ] || echo 256 > $part/keysize
	[ -f $part/ivalgorithm ] || echo cbc-essiv:sha256 > $part/ivalgorithm
	[ -f $part/keytype ] || echo passphrase > $part/keytype
	[ -f $part/keyhash ] || echo sha256 > $part/keyhash
	;;
    luks)
	[ -f $part/cipher ] || echo aes > $part/cipher
	[ -f $part/keysize ] || echo 256 > $part/keysize
	[ -f $part/ivalgorithm ] || echo cbc-essiv:sha256 > $part/ivalgorithm
	[ -f $part/keytype ] || echo passphrase > $part/keytype
	[ -f $part/keyhash ] || echo sha256 > $part/keyhash
	;;
esac

