#!/bin/sh

. /lib/partman/crypto_tools.sh

type=$1
dev=$2
id=$3
part=$dev/$id

[ -d $part ] || mkdir $part
rm -f $part/use_filesystem
rm -f $part/format

echo crypto > $part/method
echo loop-AES > $part/crypto_type

crypto_set_defaults $part loop-AES
