#!/bin/sh

. /usr/share/debconf/confmodule

set -e

dev=$1
id=$2
part=$dev/$id

cd $dev

choice_crypt_type () {
    if [ -f $part/crypt_type ]; then
        type=$(cat $part/crypt_type)
        db_metaget partman-crypto/text/crypt_type/$type description
	crypt_type="$RET"
    else
        db_metaget partman-basicfilesystems/text/no_mountpoint description
        crypt_type="$RET"
    fi

    db_metaget partman-crypto/text/specify_crypt_type description
    RET=$(stralign -25 "$RET")
    printf "crypttype\t%s%s\n" "$RET" "$crypt_type"
}

[ -f $part/method ] || exit 0

method=$(cat $part/method)
if [ "$method" = crypto ]; then
    choice_crypt_type
fi

