#!/bin/sh

. /lib/partman/crypto_tools.sh

dev=$1
id=$2
part=$dev/$id

[ -f $part/method ] || exit 0
[ -f $part/cipher ] || exit 0
method=$(cat $part/method)
cipher=$(cat $part/cipher)

if [ "${method%/*}" = crypto ]; then
    type=${method#*/}
    crypto_dochoice $part $type $cipher "keytype"
fi

