#!/bin/sh

# TODO:
# is keytype per cipher, or per crypt_type?
# should we use a static mapping?

. /lib/partman/definitions.sh

dev=$2
id=$3
part=$dev/$id

[ -f $part/method ] || exit 0
[ -f $part/cipher ] || exit 0

valid_keytypes () {
    case $1 in
        loop-AES)
            echo keyfile random;;
        dm-crypt)
            echo passphrase;; # ??
        luks)
            echo passphrase;; # ???
    esac
}

select_keytype () {
    crypt_type=$1
    cipher=$2

    choices=$(
        for type in $(valid_keytypes $crypt_type); do
            db_metaget partman-crypto/text/keytype/$type description
            printf "%s\t%s\n" $type "$RET"
        done
    )

    debconf_select critical partman-crypto/keytype "$choices" || return

    if [ "$RET" = none ]; then
        rm -f $part/keytype
        return
    fi
    
    echo $RET > $part/keytype
}

method=$(cat $part/method)
cipher=$(cat $part/cipher)

if [ "${method%/*}" = crypto ]; then
    crypt_type=${method#*/}
    select_keytype $crypt_type $cipher
fi

# vim:set ts=4 sw=4 expandtab:
