#!/bin/sh

. /lib/partman/definitions.sh

dev=$2
id=$3
part=$dev/$id

cd $dev

module_available () {
    test -f /var/run/partman-crypto/modules/$1
}

select_cipher () {
    crypt_type=$1

    ciphers=""
    for cipher_dir in /lib/partman/ciphers/$crypt_type/*; do
        if [ -f $cipher_dir/module ]; then
            module=$(cat $cipher_dir/module)
            if ! module_available $module; then
                continue
            fi
        fi

        name=${cipher_dir##*/}
        desc=$(cat $cipher_dir/desc)
        if [ "$ciphers" ]; then
            ciphers="$ciphers, $name - $desc"
        else
            ciphers="$name - $desc"
        fi
    done

    template="partman-crypto/cipher"
    db_subst $template choices $ciphers
    db_input critical $template || true
    db_go || return
    db_get $template
    
    if [ "$RET" = none ]; then
        rm -f $part/cipher
        return
    fi
    
    echo ${RET%% *} > $part/cipher
}

[ -f $part/method ] || exit 0
[ -f $part/crypt_type ] || exit 0

method=$(cat $part/method)
if [ "$method" = crypto ]; then
    type=$(cat $part/crypt_type)
    select_cipher $type
fi

