#!/bin/sh

. /lib/partman/definitions.sh

dev=$2
id=$3
part=$dev/$id

cd $dev

modules=/var/run/partman-crypto/modules

module_is_loaded () {
    test -f $modules/$1
}

load_modules () {
    cipher_dir=$1
    for module in $(cat $cipher_dir/module); do
        if ! module_is_loaded $module; then
            if modprobe -q $module; then
                touch $modules/$module
            else
                rm -f $modules/$module
                return 1
            fi
        fi
    done
    return 0
}

select_cipher () {
    type=$1
    ciphers=""
    for cipher_dir in /lib/partman/ciphers/$type/*; do
        if [ -f $cipher_dir/module ]; then
            if ! load_modules $cipher_dir; then
                continue
            fi
        fi
        name=${cipher_dir##*/}
        desc=$(cat $cipher_dir/desc)
        if [ "$ciphers" ]; then
            ciphers="$ciphers, $name"
        else
            ciphers="$name"
        fi
    done

    template="partman-crypto/cipher"
    db_subst $template choices $ciphers
    db_input critical $template || true
    db_go || return
    db_get $template
    
    if [ "$RET" = none ]; then
        rm -f $part/cipher
        return
    fi
    
    echo ${RET%% *} > $part/cipher
}

[ -f $part/method ] || exit 0
method=$(cat $part/method)

if [ "${method%/*}" = crypto ]; then
    type=${method#*/}
    select_cipher $type
fi

