#!/bin/sh

# Installs userspace tools and helper packages in the target system. This 
# is responsible for installing loop-aes-utils and loop-aes-rootfs (TODO)
# for loop-AES and cryptsetup for dm-crypt/luks.

. /lib/partman/definitions.sh

loop_AES=no
dm_crypt=no
luks=no

install_loopkeys () {
    dir=/target/etc/loopkeys
    if [ ! -d $dir ]; then
        mkdir -p $dir
        chmod 0700 $dir
    fi

    for key in $*; do
        if [ -f $dir/$key ]; then
            : TODO show error
        else 
            mv $key $dir
	    chmod 0600 $dir/$key
        fi
    done
}

for dev in $DEVICES/*; do
    [ -d "$dev" ] || continue
    cd $dev
    open_dialog PARTITIONS
    while { read_line num id size type fs path name; [ "$id" ]; }; do
        [ "$fs" != free ] || continue
        [ -f $id/method ] || continue

        method=$(cat $id/method)
        type=${method#*/}
        case $type in
            loop-AES)
                loop_AES=yes
                install_loopkeys $id/*.gpg
                ;;
            dm-crypt)
                dm_crypt=yes
                ;;
            luks)
                luks=yes
                ;;
        esac
    done
    close_dialog
done

if [ $loop_AES = yes ]; then
    # TODO loop-aes-rootfs
    apt-install loop-aes-utils
fi

if [ $dm_crypt = yes ] || [ $luks = yes ]; then
    apt-install cryptsetup
fi

