#!/bin/sh

# Show an error if the root filesystem is to be stored on an encrypted 
# partition, which is still unimplemented.

. /lib/partman/definitions.sh

for dev in $DEVICES/*; do
    [ -d "$dev" ] || continue
    cd $dev
    partitions=
    open_dialog PARTITIONS
    while { read_line num id size type fs path name; [ "$id" ]; }; do
        [ "$fs" != free ] || continue
        partitions="$partitions $id,$path"
    done
    close_dialog
    
    # "is crypto?"
    [ -f crypt_realdev ] || continue

    for part in $partitions; do
        id=${part%,*}
        path=${part#*,}

        [ -f $id/method ] || continue
        [ -f $id/mountpoint ] || continue
        mnt=$(cat $id/mountpoint)

        r=$(cat crypt_realdev)
        set -- $(IFS=: && echo $r)
        realdev=$1
        realdevnum=$2
        realdevdir=$3

        [ -f $realdevdir/method ] || continue
        method=$(cat $realdevdir/method)

        if [ $method = crypto ] && [ $mnt = / ]; then
            templ="partman-crypto/crypto_root_unimplemented"
            db_set $templ false
            db_fset $templ seen false
            db_input critical $templ
            db_go || true
            exit 1
        fi
    done
done

# vim:set ts=4 sw=4 expandtab:
