#!/bin/sh -e
# This scripts loads the modules required for the default setups
# of loop-AES, dm-crypt and LUKS. Other optional modules will be
# loaded later in active_partition/cipher/do_option.

modules=/var/run/partman-crypto/modules
if [ -d $modules ]; then
    exit 0
fi

mkdir -p $modules

load_module () {
    if modprobe -q $1; then
        touch $modules/$1
    else
        rm -f $modules/$1
    fi
 }
 
# loop-AES module (includes AES)
load_module loop-aes

# TODO: add modules required for dm-crypt, and luks

